(function () {
  'use strict';
  function xml(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c]; }); }
  function colName(n) { var result = ''; do { result = String.fromCharCode(65 + n % 26) + result; n = Math.floor(n / 26) - 1; } while (n >= 0); return result; }
  function dateSerial(value) { return Math.floor(new Date(value + 'T00:00:00Z') / 86400000) + 25569; }
  function minutes(start, end) { var a = start.split(':').map(Number), b = end.split(':').map(Number), n = b[0] * 60 + b[1] - a[0] * 60 - a[1]; return n <= 0 ? n + 1440 : n; }
  function cell(value, row, col, dateCols) { var ref = colName(col) + (row + 1), style = row === 0 ? 1 : (dateCols.indexOf(col) >= 0 ? 2 : (typeof value === 'number' ? 3 : 0)); if (typeof value === 'number') return '<c r="' + ref + '" s="' + style + '"><v>' + value + '</v></c>'; return '<c r="' + ref + '" t="inlineStr" s="' + style + '"><is><t>' + xml(value) + '</t></is></c>'; }
  function sheetXml(sheet) { var cols = sheet.widths.map(function (w, i) { return '<col min="' + (i + 1) + '" max="' + (i + 1) + '" width="' + w + '" customWidth="1"/>'; }).join(''), rows = sheet.rows.map(function (values, r) { return '<row r="' + (r + 1) + '">' + values.map(function (v, c) { return cell(v, r, c, sheet.dateCols); }).join('') + '</row>'; }).join(''), end = colName(sheet.rows[0].length - 1) + Math.max(1, sheet.rows.length); return '<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>' + cols + '</cols><sheetData>' + rows + '</sheetData><autoFilter ref="A1:' + end + '"/></worksheet>'; }
  function workbookFiles(sheets) {
    var contentTypes = '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>' + sheets.map(function (_, i) { return '<Override PartName="/xl/worksheets/sheet' + (i + 1) + '.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'; }).join('') + '</Types>';
    var rootRels = '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
    var workbook = '<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>' + sheets.map(function (s, i) { return '<sheet name="' + xml(s.name) + '" sheetId="' + (i + 1) + '" r:id="rId' + (i + 1) + '"/>'; }).join('') + '</sheets></workbook>';
    var relationships = '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' + sheets.map(function (_, i) { return '<Relationship Id="rId' + (i + 1) + '" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet' + (i + 1) + '.xml"/>'; }).join('') + '<Relationship Id="rId' + (sheets.length + 1) + '" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';
    var styles = '<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF126B63"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0"/><xf numFmtId="14" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="2" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs></styleSheet>';
    var files = { '[Content_Types].xml': contentTypes, '_rels/.rels': rootRels, 'xl/workbook.xml': workbook, 'xl/_rels/workbook.xml.rels': relationships, 'xl/styles.xml': styles };
    sheets.forEach(function (s, i) { files['xl/worksheets/sheet' + (i + 1) + '.xml'] = sheetXml(s); }); return files;
  }
  var crcTable;
  function crc32(bytes) { if (!crcTable) { crcTable = new Uint32Array(256); for (var n = 0; n < 256; n++) { var c = n; for (var k = 0; k < 8; k++) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1; crcTable[n] = c >>> 0; } } var value = 0xffffffff; bytes.forEach(function (b) { value = crcTable[(value ^ b) & 255] ^ (value >>> 8); }); return (value ^ 0xffffffff) >>> 0; }
  function zip(files) { var encoder = new TextEncoder(), locals = [], central = [], offset = 0, count = 0; Object.keys(files).forEach(function (name) { var nameBytes = encoder.encode(name), bytes = encoder.encode(files[name]), crc = crc32(bytes), local = new Uint8Array(30 + nameBytes.length + bytes.length), view = new DataView(local.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint32(14, crc, true); view.setUint32(18, bytes.length, true); view.setUint32(22, bytes.length, true); view.setUint16(26, nameBytes.length, true); local.set(nameBytes, 30); local.set(bytes, 30 + nameBytes.length); locals.push(local); var cd = new Uint8Array(46 + nameBytes.length), cv = new DataView(cd.buffer); cv.setUint32(0, 0x02014b50, true); cv.setUint16(4, 20, true); cv.setUint16(6, 20, true); cv.setUint32(16, crc, true); cv.setUint32(20, bytes.length, true); cv.setUint32(24, bytes.length, true); cv.setUint16(28, nameBytes.length, true); cv.setUint32(42, offset, true); cd.set(nameBytes, 46); central.push(cd); offset += local.length; count++; }); var centralSize = central.reduce(function (n, x) { return n + x.length; }, 0), end = new Uint8Array(22), ev = new DataView(end.buffer); ev.setUint32(0, 0x06054b50, true); ev.setUint16(8, count, true); ev.setUint16(10, count, true); ev.setUint32(12, centralSize, true); ev.setUint32(16, offset, true); var output = new Uint8Array(offset + centralSize + 22), pos = 0; locals.concat(central).concat([end]).forEach(function (x) { output.set(x, pos); pos += x.length; }); return output; }
  function download(data, from, to, selectedIds, employeeName, storeName) {
    try {
      var included = function (id) { return !selectedIds || selectedIds.indexOf(id) >= 0; }, shifts = data.shifts.filter(function (x) { return x.date >= from && x.date <= to && included(x.employeeId); }), absences = data.absences.filter(function (x) { return x.date >= from && x.date <= to && included(x.employeeId); });
      var detail = [['Data', 'Dipendente', 'Negozio', 'Intervallo', 'Entrata', 'Uscita', 'Ore', 'Nota']];
      shifts.forEach(function (x) { x.intervals.forEach(function (i, n) { detail.push([dateSerial(x.date), employeeName(x.employeeId), storeName(x.storeId), n + 1, i.start, i.end, Math.round(minutes(i.start, i.end) / 60 * 100) / 100, n === 0 ? x.note || '' : '']); }); });
      var groups = {}; shifts.forEach(function (x) { var key = x.employeeId + '|' + x.storeId; if (!groups[key]) groups[key] = { employee: employeeName(x.employeeId), store: storeName(x.storeId), turns: 0, mins: 0 }; groups[key].turns += x.intervals.length; x.intervals.forEach(function (i) { groups[key].mins += minutes(i.start, i.end); }); });
      var summary = [['Dipendente', 'Negozio', 'Turni', 'Ore totali']]; Object.keys(groups).forEach(function (key) { var x = groups[key]; summary.push([x.employee, x.store, x.turns, Math.round(x.mins / 60 * 100) / 100]); });
      var absenceRows = [['Data', 'Dipendente', 'Tipo', 'Nota']]; absences.forEach(function (x) { absenceRows.push([dateSerial(x.date), employeeName(x.employeeId), x.type, x.note || '']); });
      var bytes = zip(workbookFiles([{ name: 'Dettaglio turni', rows: detail, dateCols: [0], widths: [13, 25, 22, 12, 11, 11, 12, 30] }, { name: 'Riepilogo', rows: summary, dateCols: [], widths: [25, 22, 12, 15] }, { name: 'Assenze', rows: absenceRows, dateCols: [0], widths: [13, 25, 20, 30] }]));
      var blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'riepilogo-ore-' + from + '_' + to + '.xlsx'; a.click(); setTimeout(function () { URL.revokeObjectURL(a.href); }, 1000);
    } catch (error) { alert('Non è stato possibile creare il file Excel.'); console.error(error); }
  }
  window.XlsxExporter = { download: download, _test: { workbookFiles: workbookFiles, zip: zip } };
})();
